### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by sandman18** [lukeed/freshie#13] opened 2020-11-19 15:10 UTC
Hi Luke,

I'm getting this error for my cloudflare worker:

Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught Error: Some functionality, such as asynchronous I/O, timeouts, and generating random values, can only be performed while handling a request.\n  at line 1 in t\n  at line 1 in n\n  at line 1 in wake\n  at line 1 in Qt\n  at line 1 in Wt\n  at line 1\n  at line 1 in registerPlugin\n  at line 1\n  at line 1 in n\n  at line 1\n"
    }
  ],
  "messages": []
}

Any idea what this is?

Thanks

**Comment by lukeed** [comment] 2020-11-19 22:06
Hey, no idea based on this alone.

If you can send or invite me to a reproduction, I'll take a look. Can find me elsewhere if you need to keep it private

**Comment by sandman18** [comment] 2020-11-20 00:19
I sent you an invite. ---- On Thu, 19 Nov 2020 17:06:15 -0500  notifications@github.com  wrote ----
Hey, no idea based on this alone.
If you can send or invite me to a reproduction, I'll take a look. Can find me elsewhere if you need to keep it private

**Comment by lukeed** [comment] 2020-11-20 19:10
Closing as we've taken care of this 👍 

Had to do with the GSAP animation library being loaded within the Worker runtime code. 
Might need to think of a way to handle this easily, since it's likely to show up frequently with varying browser-facing libraries.

**Closed by lukeed** 2020-11-20 19:10 UTC
